# 14.1 How computers see: images as tensors

Gradient Descent · Track 14 (Computer Vision). Runnable companion — outputs match the lesson.


## An image is a grid of numbers (a tensor)


In [1]:
import numpy as np
img = np.array([[[255,0,0],[0,255,0]],
                [[0,0,255],[255,255,0]]])     # a 2x2 RGB image
print("shape (H, W, channels):", img.shape)
print("top-left pixel [R,G,B]:", img[0,0])
gray = img.mean(axis=2).round().astype(int)    # grayscale = average the 3 channels
print("grayscale:\n", gray)


shape (H, W, channels): (2, 2, 3)
top-left pixel [R,G,B]: [255   0   0]
grayscale:
 [[ 85  85]
 [ 85 170]]


## Explore: channels carry the picture, and normalization


In [2]:
# Each channel is a 2-D grid; the model sees only numbers.
for name, c in zip("RGB", range(3)):
    print(name, "channel:\n", img[:,:,c])
# Pixels are 0-255; models usually scale them to [0,1] (or standardize).
print("\nnormalized top-left pixel:", (img[0,0]/255).round(3))


R channel:
 [[255   0]
 [  0 255]]
G channel:
 [[  0 255]
 [  0 255]]
B channel:
 [[  0   0]
 [255   0]]

normalized top-left pixel: [1. 0. 0.]
