# 14.2 Image classification & CNN architectures

Gradient Descent · Track 14 (Computer Vision). Runnable companion — outputs match the lesson.


## One convolution by hand: an edge detector over a square


In [1]:
import numpy as np
img = np.array([[0,0,0,0,0],
                [0,9,9,9,0],
                [0,9,9,9,0],
                [0,9,9,9,0],
                [0,0,0,0,0]], float)
kernel = np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1]], float)   # edge detector
H,W,k = *img.shape, 3
out = np.zeros((H-k+1, W-k+1))
for i in range(H-k+1):
    for j in range(W-k+1):
        out[i,j] = (img[i:i+k, j:j+k] * kernel).sum()          # multiply + sum
print("feature map:\n", out.astype(int))


feature map:
 [[45 27 45]
 [27  0 27]
 [45 27 45]]


## Explore: the filter fires on the border, stays silent in flat interior


In [2]:
# The center (interior of the square) is flat -> response 0.
# The corners/edges (transition light<->dark) -> large response.
print("center response:", int(out[1,1]), "(flat interior -> no edge)")
print("corner response:", int(out[0,0]), "(a border -> strong edge)")
# The same 3x3 filter was reused at every position: weight sharing.


center response: 0 (flat interior -> no edge)
corner response: 45 (a border -> strong edge)
