# 14.5 Vision Transformers: attention for images

Gradient Descent · Track 14 (Computer Vision). Runnable companion — outputs match the lesson.


## Patchify: turn an image into a sequence of patch-tokens


In [1]:
import numpy as np
img = np.array([[ 0,  1,  2,  3],
                [ 4,  5,  6,  7],
                [ 8,  9, 10, 11],
                [12, 13, 14, 15]])
P = 2                                   # patch size: 2x2
patches = []
for r in range(0, 4, P):                # step over patch rows
    for c in range(0, 4, P):            # step over patch cols
        patch = img[r:r+P, c:c+P]       # grab a 2x2 block
        patches.append(patch.flatten()) # flatten it into a token vector
patches = np.array(patches)
print("num patches:", patches.shape[0])
print("each patch length:", patches.shape[1])
print("patch matrix (each row = one flattened patch = one token):")
print(patches)


num patches: 4
each patch length: 4
patch matrix (each row = one flattened patch = one token):
[[ 0  1  4  5]
 [ 2  3  6  7]
 [ 8  9 12 13]
 [10 11 14 15]]


## Explore: token count grows with the square as patches shrink


In [2]:
# A 224x224 image with PxP patches -> (224/P)^2 tokens.
# Attention cost ~ tokens^2, so smaller patches get expensive fast.
for P in [32, 16, 8]:
    n = (224//P)**2
    print(f"patch {P:>2}x{P:<2} -> {n:>4} tokens, attention cost ~ {n**2:,}")


patch 32x32 ->   49 tokens, attention cost ~ 2,401
patch 16x16 ->  196 tokens, attention cost ~ 38,416
patch  8x8  ->  784 tokens, attention cost ~ 614,656
