# 4.6 Convolutional Neural Networks

Gradient Descent · Track 4 (Deep Learning). Runnable NumPy-from-scratch companion — outputs match the lesson.

## One 2-D convolution by hand (vertical-edge filter)

In [1]:
import numpy as np
image = np.array([[3,1,2,0,1],[0,4,1,2,3],[1,2,3,1,0],[2,0,1,4,2],[1,3,2,0,1]], float)
kernel = np.array([[1,0,-1],[1,0,-1],[1,0,-1]], float)
kh, kw = kernel.shape
out = np.zeros((image.shape[0]-kh+1, image.shape[1]-kw+1))
for i in range(out.shape[0]):
    for j in range(out.shape[1]):
        out[i,j] = (image[i:i+kh, j:j+kw] * kernel).sum()
print(out)

[[-2.  4.  2.]
 [-2. -1.  0.]
 [-2.  0.  3.]]
