# 5.5 Self-attention & multi-head attention

Gradient Descent · Track 5 (NLP & Transformers). Runnable NumPy companion — outputs match the lesson.

## Full self-attention on a sequence: softmax(QKᵀ/√d)·V

In [1]:
import numpy as np
def softmax(x):
    e = np.exp(x - x.max(axis=-1, keepdims=True))
    return e / e.sum(axis=-1, keepdims=True)
X = np.array([[1,0,1,0],[0,1,0,1],[1,1,0,0]], float)
d = X.shape[1]
Q = K = V = X
scores = Q @ K.T / np.sqrt(d)
A = softmax(scores)
output = A @ V
print("attention matrix (rows sum to 1):\n", A.round(2))
print("row sums:", A.sum(axis=1).round(3))
print("output:\n", output.round(2))

attention matrix (rows sum to 1):
 [[0.51 0.19 0.31]
 [0.19 0.51 0.31]
 [0.27 0.27 0.45]]
row sums: [1. 1. 1.]
output:
 [[0.81 0.49 0.51 0.19]
 [0.49 0.81 0.19 0.51]
 [0.73 0.73 0.27 0.27]]
