# Lesson 2.2 — NumPy arrays & vectorization

In [1]:
import numpy as np
a = np.arange(12).reshape(3,4)
print("shape:", a.shape, "dtype:", a.dtype)
print(a)

shape: (3, 4) dtype: int64
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Vectorization beats a loop

In [2]:
import time
rng = np.random.default_rng(0); x = rng.normal(50,10,size=1_000_000); mu,sd = x.mean(), x.std()
t=time.perf_counter()
z=np.empty_like(x)
for i in range(x.size): z[i]=(x[i]-mu)/sd
loop=time.perf_counter()-t
t=time.perf_counter(); zv=(x-mu)/sd; vec=time.perf_counter()-t
print(f"loop {loop:.3f}s  vectorized {vec:.4f}s  speedup ~{loop/vec:.0f}x  same={np.allclose(z,zv)}")

loop 0.366s  vectorized 0.0173s  speedup ~21x  same=True


## Boolean masks read and write

In [3]:
big = x[x>70]; print("count>70:", big.size, " mean:", round(big.mean(),2))
y = np.array([-3,5,-1,8.]); y[y<0]=0; print("clipped:", y)

count>70: 23017  mean: 73.72
clipped: [0. 5. 0. 8.]
